### ISSUE TITLE
Hitboxen

### ISSUE THREAD

**Issue by PaulicStudios** [42core-team/core#117]

**Comment by Reptudn** [comment]
please provide more information @PaulicStudios

**Comment by PaulicStudios** [comment]
With hitboxen I mean that units can not be stacked anymore and so that they have a "real" place on the map where only one unit can be. For that to work we will have to implement some sort of basic pathfinding and when the player wants to do something more advanced they have to do their own.

**Comment by PaulicStudios** [comment]
Will be automatically implemented by the grid system...
